### ISSUE TITLE
translate to spanish about/questions

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit.mysociety.org#74]
![helpacerca](https://cloud.githubusercontent.com/assets/428820/4964495/fe82158e-672e-11e4-8029-93c22970fe82.png)

Its possible translate it all to spanish i collaborate with that

**Comment by duncanparkes** [comment]
Obviously it would be helpful to us to have the page in Spanish, and as of f8baf4286c2e5be0a9704077744a6175b6a77884, I've made it so you can translate this page. For your own site I expect you'll actually want to vary the content rather than just translate it, which you can do by making your own about/questions.html template.

**Comment by johnfelipe** [comment]
Translate it in this moment, tnks
